name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml   # keep anything extra you need

      - name: Run tests & compare CPU traces
        run: |
          pytest -q            # your existing tests
          python -m cosim.run_vs_pyboy   # produces mismatch_log.csv

      # ――― NEW: upload the CSV (even if it’s empty except header) ―――
      - name: Upload mismatch log
        uses: actions/upload-artifact@v4
        with:
          name: mismatch_log
          path: mismatch_log.csv
